name: Docker Publish

on:
  push:
    branches: [ master ] 
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare image metadata (lowercase owner and repo)
        id: meta 
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME_LC=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]') # Get repo name and lowercase it
          echo "owner_lc=${OWNER_LC}" >> $GITHUB_OUTPUT
          echo "backend_image_name=${REPO_NAME_LC}/fauxpas-backend" >> $GITHUB_OUTPUT
          echo "frontend_image_name=${REPO_NAME_LC}/fauxpas-frontend" >> $GITHUB_OUTPUT
          echo "ml_api_image_name=${REPO_NAME_LC}/fauxpas-ml-api" >> $GITHUB_OUTPUT
          # For the simple case where image name is just the sub-project name:
          # echo "backend_image_name_simple=fauxpas-backend" >> $GITHUB_OUTPUT 
          # (and use this if you prefer simpler image names directly under the owner)

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/${{ steps.meta.outputs.backend_image_name }}:latest
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/${{ steps.meta.outputs.backend_image_name }}:${{ github.sha }}
            ${{ startsWith(github.ref, 'refs/tags/') && format('ghcr.io/{0}/{1}:{2}', steps.meta.outputs.owner_lc, steps.meta.outputs.backend_image_name, github.ref_name) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/${{ steps.meta.outputs.frontend_image_name }}:latest
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/${{ steps.meta.outputs.frontend_image_name }}:${{ github.sha }}
            ${{ startsWith(github.ref, 'refs/tags/') && format('ghcr.io/{0}/{1}:{2}', steps.meta.outputs.owner_lc, steps.meta.outputs.frontend_image_name, github.ref_name) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push ML API image
        uses: docker/build-push-action@v5
        with:
          context: ./ml_api
          file: ./ml_api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/${{ steps.meta.outputs.ml_api_image_name }}:latest
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/${{ steps.meta.outputs.ml_api_image_name }}:${{ github.sha }}
            ${{ startsWith(github.ref, 'refs/tags/') && format('ghcr.io/{0}/{1}:{2}', steps.meta.outputs.owner_lc, steps.meta.outputs.ml_api_image_name, github.ref_name) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max